import {Platform, StyleSheet, Text, View} from 'react-native';
import {
  heightPixel,
  pixelSizeHorizontal,
  pixelSizeVertical,
  widthPixel,
} from '../../Utils/constants';
export default StyleSheet.create({
  Container: {
    flex: 1,
    // backgroundColor: colors.background,
    paddingHorizontal: pixelSizeHorizontal(8),
  },
  EnterMView: {
    marginBottom: pixelSizeVertical(60),
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  DefinedMessage: {
    borderWidth: 1,
    // borderColor: colors.buttoncolorBlue,
    borderRadius: 20,
    width: 'auto',
    padding: 12,
    display: 'flex',
    flexDirection: 'row',
    marginRight: 10,
    height: 50,
  },
  LastMView: {
    maxHeight: 70,
    padding: 10,
  },
  ChatMView: {
    flex: 12,
    backgroundColor: 'white',
    justifyContent: 'flex-end',
    color: 'black',
    paddingTop: 20,
    height: '100%',
  },
  RightMessageView: {
    backgroundColor: '#6583F3',
    width: 'auto',
    maxWidth: 300,
    borderRadius: 10,
    display: 'flex',
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    padding: 15,
  },
  ImageMessageView: {
    width: 'auto',
    maxWidth: 300,
    borderRadius: 10,
    display: 'flex',
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  LeftMessageView: {
    backgroundColor: '#e7eced',
    width: 'auto',
    maxWidth: 250,
    borderRadius: 10,
    display: 'flex',
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-start',
    padding: 15,
  },
  TextMessage: {
    fontWeight: '500',
    letterSpacing: 0.9,
    color: 'white',
  },
  LeftTextMessage : {
    fontWeight: '500',
    letterSpacing: 0.9,
    color: 'black',
  },
  EnterMessageView: {
    width: '90%',
    height: heightPixel(98),
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#DAE5FF',
    flexDirection: 'row',
    paddingHorizontal: pixelSizeHorizontal(4),
  },

  IconStyle: {
    marginTop:
      Platform.OS == 'ios' ? pixelSizeVertical(10) : pixelSizeVertical(20),
  },
  SeprentStyle: {},
  Transform: {
    transform: [{rotate: '45deg'}],
  },
  leftChat: {
    display: 'flex',
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'flex-end',
    marginBottom: 10,
  },
  rightChat: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 10,
    gap: 5,
  },
  MButtons: {
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
    marginTop: 20,
  },
  UserName: {
    fontWeight: '700',
    letterSpacing: 1,
    marginBottom: 2,
  },
  RecordingM: {
    padding: 20,
    display: 'none',
  },
  RecordingView: {
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row-reverse',
    borderColor: 'grey',
    borderWidth: 1,
    padding: 10,
    borderRadius: 20,
  },
  RecordingC: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  BottomSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    height: 'auto',
    padding: 20,
    borderRadius: 10,
  },
  RecordingMic: {
    backgroundColor: 'black',
    width: heightPixel(90),
    height: heightPixel(90),
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: 2,
  },
  SendRecord: {
    backgroundColor: 'blue',
    width: heightPixel(90),
    height: heightPixel(90),
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  AudioMessage: {
    backgroundColor: '#92cfd4',
    width: 'auto',
    maxWidth: 300,
    borderRadius: 10,
    display: 'flex',
    color: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'flex-end',
    flexDirection: 'row',
    padding: 15,
  },
});
